sudo: required
services:
  - docker

before_install:
  - docker build -t francoismercadal/docker_tutorial -f Dockerfile.dev .

script:
  - docker run -e CI=true francoismercadal/docker_tutorial npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: ""
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
